from a2a.types import AgentCapabilities, AgentCard, AgentSkill

register_skill = AgentSkill(
    id="register",
    name="Register",
    description="Register the white agent with the green agent",
    tags=["register"],
)

distribute_problem_skill = AgentSkill(
    id="distribute_problem",
    name="Distribute Problem",
    description="Distribute a new coding problem to the white agent",
    tags=["distribute_problem"],
)

process_answer_skill = AgentSkill(
    id="process_answer",
    name="Process Answer",
    description="Process the answer from the white agent",
    tags=["process_answer"],
)

agent_card = AgentCard(
    name="Coding Evaluation Agent",
    description="The eval agent that evaluates code generated by white agents",
    url="http://localhost:9999/",
    version="1.0.0",
    default_input_modes=["text"],
    default_output_modes=["text"],
    capabilities=AgentCapabilities(streaming=False),
    skills=[register_skill, distribute_problem_skill, process_answer_skill],
    supports_authenticated_extended_card=False,
)
